// ================================================================
// SmartGPA - University Grading Presets
// ================================================================

export const UNI_PRESETS = {
  sliit: {
    name: 'SLIIT (Standard 4.0)',
    maxGpa: 4.0,
    grades: [
      { grade: 'A+', points: 4.00, markMin: 80, markMax: 100 },
      { grade: 'A',  points: 4.00, markMin: 75, markMax: 79 },
      { grade: 'A-', points: 3.75, markMin: 70, markMax: 74 },
      { grade: 'B+', points: 3.50, markMin: 65, markMax: 69 },
      { grade: 'B',  points: 3.00, markMin: 60, markMax: 64 },
      { grade: 'B-', points: 2.75, markMin: 55, markMax: 59 },
      { grade: 'C+', points: 2.50, markMin: 50, markMax: 54 },
      { grade: 'C',  points: 2.00, markMin: 45, markMax: 49 },
      { grade: 'C-', points: 1.75, markMin: 40, markMax: 44 },
      { grade: 'D+', points: 1.50, markMin: 35, markMax: 39 },
      { grade: 'D',  points: 1.00, markMin: 30, markMax: 34 },
      { grade: 'E',  points: 0.00, markMin: 0,  markMax: 29 },
    ],
    classifications: [
      { label: 'First Class',  minGpa: 3.70 },
      { label: 'Second Upper', minGpa: 3.30 },
      { label: 'Second Lower', minGpa: 3.00 },
      { label: 'General Pass', minGpa: 2.00 },
    ],
  },
  uom: {
    name: 'University of Moratuwa (4.2 Scale)',
    maxGpa: 4.2,
    grades: [
      { grade: 'A+', points: 4.20, markMin: 85, markMax: 100 },
      { grade: 'A',  points: 4.00, markMin: 75, markMax: 84 },
      { grade: 'A-', points: 3.70, markMin: 70, markMax: 74 },
      { grade: 'B+', points: 3.30, markMin: 65, markMax: 69 },
      { grade: 'B',  points: 3.00, markMin: 60, markMax: 64 },
      { grade: 'B-', points: 2.70, markMin: 55, markMax: 59 },
      { grade: 'C+', points: 2.30, markMin: 50, markMax: 54 },
      { grade: 'C',  points: 2.00, markMin: 45, markMax: 49 },
      { grade: 'C-', points: 1.50, markMin: 40, markMax: 44 },
      { grade: 'D',  points: 1.00, markMin: 35, markMax: 39 },
      { grade: 'F',  points: 0.00, markMin: 0,  markMax: 34 },
    ],
    classifications: [
      { label: 'First Class',  minGpa: 3.70 },
      { label: 'Second Upper', minGpa: 3.30 },
      { label: 'Second Lower', minGpa: 3.00 },
      { label: 'General Pass', minGpa: 2.00 },
    ],
  },
  uoc: {
    name: 'University of Colombo / UCSC (4.0)',
    maxGpa: 4.0,
    grades: [
      { grade: 'A+', points: 4.00, markMin: 90, markMax: 100 },
      { grade: 'A',  points: 4.00, markMin: 85, markMax: 89 },
      { grade: 'A-', points: 3.70, markMin: 75, markMax: 84 },
      { grade: 'B+', points: 3.30, markMin: 70, markMax: 74 },
      { grade: 'B',  points: 3.00, markMin: 65, markMax: 69 },
      { grade: 'B-', points: 2.70, markMin: 60, markMax: 64 },
      { grade: 'C+', points: 2.30, markMin: 55, markMax: 59 },
      { grade: 'C',  points: 2.00, markMin: 50, markMax: 54 },
      { grade: 'C-', points: 1.70, markMin: 45, markMax: 49 },
      { grade: 'D+', points: 1.30, markMin: 40, markMax: 44 },
      { grade: 'D',  points: 1.00, markMin: 30, markMax: 39 },
      { grade: 'E',  points: 0.00, markMin: 0,  markMax: 29 },
    ],
    classifications: [
      { label: 'First Class',  minGpa: 3.70 },
      { label: 'Second Upper', minGpa: 3.30 },
      { label: 'Second Lower', minGpa: 3.00 },
      { label: 'General Pass', minGpa: 2.00 },
    ],
  },
  usjp: {
    name: 'University of Sri Jayewardenepura (USJP)',
    maxGpa: 4.0,
    grades: [
      { grade: 'A+', points: 4.00, markMin: 85, markMax: 100 },
      { grade: 'A',  points: 4.00, markMin: 75, markMax: 84 },
      { grade: 'A-', points: 3.70, markMin: 70, markMax: 74 },
      { grade: 'B+', points: 3.30, markMin: 65, markMax: 69 },
      { grade: 'B',  points: 3.00, markMin: 60, markMax: 64 },
      { grade: 'B-', points: 2.70, markMin: 55, markMax: 59 },
      { grade: 'C+', points: 2.30, markMin: 50, markMax: 54 },
      { grade: 'C',  points: 2.00, markMin: 45, markMax: 49 },
      { grade: 'C-', points: 1.70, markMin: 40, markMax: 44 },
      { grade: 'D',  points: 1.00, markMin: 35, markMax: 39 },
      { grade: 'E',  points: 0.00, markMin: 0,  markMax: 34 },
    ],
    classifications: [
      { label: 'First Class',  minGpa: 3.70 },
      { label: 'Second Upper', minGpa: 3.30 },
      { label: 'Second Lower', minGpa: 3.00 },
      { label: 'General Pass', minGpa: 2.00 },
    ],
  },
  nsbm_iit: {
    name: 'NSBM / IIT (Standard 4.0)',
    maxGpa: 4.0,
    grades: [
      { grade: 'A+', points: 4.00, markMin: 85, markMax: 100 },
      { grade: 'A',  points: 4.00, markMin: 75, markMax: 84 },
      { grade: 'A-', points: 3.70, markMin: 70, markMax: 74 },
      { grade: 'B+', points: 3.30, markMin: 65, markMax: 69 },
      { grade: 'B',  points: 3.00, markMin: 60, markMax: 64 },
      { grade: 'B-', points: 2.70, markMin: 55, markMax: 59 },
      { grade: 'C+', points: 2.30, markMin: 50, markMax: 54 },
      { grade: 'C',  points: 2.00, markMin: 45, markMax: 49 },
      { grade: 'D',  points: 1.00, markMin: 40, markMax: 44 },
      { grade: 'E',  points: 0.00, markMin: 0,  markMax: 39 },
    ],
    classifications: [
      { label: 'First Class',  minGpa: 3.70 },
      { label: 'Second Upper', minGpa: 3.30 },
      { label: 'Second Lower', minGpa: 3.00 },
      { label: 'General Pass', minGpa: 2.00 },
    ],
  },
  custom: {
    name: 'Custom (User Defined)',
    maxGpa: 4.0,
    grades: [
      { grade: 'A+', points: 4.00, markMin: 90, markMax: 100 },
      { grade: 'A',  points: 4.00, markMin: 85, markMax: 89 },
      { grade: 'A-', points: 3.75, markMin: 80, markMax: 84 },
      { grade: 'B+', points: 3.50, markMin: 75, markMax: 79 },
      { grade: 'B',  points: 3.00, markMin: 70, markMax: 74 },
      { grade: 'B-', points: 2.75, markMin: 65, markMax: 69 },
      { grade: 'C+', points: 2.50, markMin: 60, markMax: 64 },
      { grade: 'C',  points: 2.00, markMin: 55, markMax: 59 },
      { grade: 'C-', points: 1.75, markMin: 50, markMax: 54 },
      { grade: 'D+', points: 1.50, markMin: 45, markMax: 49 },
      { grade: 'D',  points: 1.00, markMin: 40, markMax: 44 },
      { grade: 'E',  points: 0.00, markMin: 0,  markMax: 39 },
    ],
    classifications: [
      { label: 'First Class',  minGpa: 3.70 },
      { label: 'Second Upper', minGpa: 3.30 },
      { label: 'Second Lower', minGpa: 3.00 },
      { label: 'General Pass', minGpa: 2.00 },
    ],
  },
};

export const DEFAULT_GRADING_SETTINGS = {
  preset: 'sliit',
  grades: JSON.parse(JSON.stringify(UNI_PRESETS.sliit.grades)),
  classifications: JSON.parse(JSON.stringify(UNI_PRESETS.sliit.classifications)),
  maxGpa: 4.0,
};
